drop table CONTENTALL;
drop sequence CONTENT_SEQ;
purge recyclebin;

create table CONTENTALL(
	CONTENTNUM number constraint CONTENTALL_PK primary key,
	CONTENTTYPE nvarchar2(10) CHECK(CONTENTTYPE IN('FOOD', 'ACTIVITY', 'HOTEL', 'LANDMARK'))
);
create sequence CONTENTALL_SEQ increment by 1 start with 1 nocache; 

insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'FOOD');

insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'ACTIVITY');

insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'HOTEL');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'HOTEL');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'HOTEL');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'HOTEL');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'HOTEL');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'HOTEL');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'HOTEL');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'HOTEL');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'HOTEL');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'HOTEL');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'HOTEL');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'HOTEL');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'HOTEL');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'HOTEL');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'HOTEL');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'HOTEL');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'HOTEL');

insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'LANDMARK');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'LANDMARK');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'LANDMARK');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'LANDMARK');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'LANDMARK');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'LANDMARK');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'LANDMARK');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'LANDMARK');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'LANDMARK');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'LANDMARK');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'LANDMARK');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'LANDMARK');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'LANDMARK');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'LANDMARK');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'LANDMARK');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'LANDMARK');
insert into CONTENTALL values(CONTENTALL_SEQ.nextval, 'LANDMARK');
commit;

